# Generated by Django 6.0.3 on 2026-03-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20260308_0054'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE PROCEDURE place_order(
                p_user_id INT,
                p_restaurant_id INT,
                p_menu_item_id INT,
                p_quantity INT
            )
            LANGUAGE plpgsql
            AS $$
            DECLARE
                v_order_id INT;
                v_item_price NUMERIC(8, 2);
                v_total_price NUMERIC(8, 2);
            BEGIN
                -- 1. Get the price of the requested menu item
                SELECT price INTO v_item_price 
                FROM delivery_menuitem 
                WHERE id = p_menu_item_id;

                -- 2. Calculate the total price
                v_total_price := v_item_price * p_quantity;

                -- 3. Create the Order and get the new auto-generated order_id
                INSERT INTO delivery_order (user_id, restaurant_id, total_price, status)
                VALUES (p_user_id, p_restaurant_id, v_total_price, 'Pending')
                RETURNING order_id INTO v_order_id;

                -- 4. Create the connected OrderItem
                INSERT INTO delivery_orderitem (order_id, menu_item_id, quantity)
                VALUES (v_order_id, p_menu_item_id, p_quantity);
                
            END;
            $$;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS place_order;"
        )
    ]