# Generated by Django 6.0.3 on 2026-03-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_order_rating'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- ====================================================
            -- TRIGGER: AUTO-UPDATE RESTAURANT RATING
            -- ====================================================
            
            -- Step A: Create the function that averages the ratings
            CREATE OR REPLACE FUNCTION update_restaurant_rating_func()
            RETURNS TRIGGER AS $$
            BEGIN
                -- Only recalculate if the user actually left a rating (ignoring NULLs)
                IF NEW.rating IS NOT NULL THEN
                    UPDATE delivery_restaurant
                    -- Assuming your primary key on Restaurant is restaurant_id
                    SET rating = (
                        SELECT COALESCE(ROUND(AVG(rating), 1), 0)
                        FROM delivery_order
                        WHERE restaurant_id = NEW.restaurant_id AND rating IS NOT NULL
                    )
                    WHERE restaurant_id = NEW.restaurant_id;
                END IF;
                
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Step B: Create the trigger that fires when a rating is updated
            CREATE TRIGGER auto_update_restaurant_rating
            AFTER UPDATE OF rating ON delivery_order
            FOR EACH ROW
            EXECUTE FUNCTION update_restaurant_rating_func();
            """,
            
            reverse_sql="""
            DROP TRIGGER IF EXISTS auto_update_restaurant_rating ON delivery_order;
            DROP FUNCTION IF EXISTS update_restaurant_rating_func();
            """
        )
    ]