# Generated by Django 6.0.3 on 2026-03-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_restaurant_location_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='location_node',
        ),
    ]
