# Generated by Django 6.0.3 on 2026-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_rename_location_restaurant_location_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
