# Generated by Django 6.0.3 on 2026-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_order_delivery_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
